build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - ./mvnw install -DskipTests
  environment:
    name: Dev


test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"

deploy-prod:
  stage: deploy
  script:
    - ./mvnw package -DskipTests
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - file="$(find . -type f -iname "FreshOnline*.jar")"
    - cp -v "$file" "ece.jar" 
    - nohup java -jar ece.jar &
    - java -jar app.jar > yourservice.log 2>&1 &
    - echo "done" 
