package com.example.freshonline.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.user_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.user_id
     *
     * @return the value of favorite.user_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.user_id
     *
     * @param userId the value for favorite.user_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.goods_id
     *
     * @return the value of favorite.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.goods_id
     *
     * @param goodsId the value for favorite.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}