package com.example.freshonline.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
@NoArgsConstructor
@AllArgsConstructor
public class SaledGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.order_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.price
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.count
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.rate
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saled_goods.comment
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.order_id
     *
     * @return the value of saled_goods.order_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.order_id
     *
     * @param orderId the value for saled_goods.order_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.goods_id
     *
     * @return the value of saled_goods.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.goods_id
     *
     * @param goodsId the value for saled_goods.goods_id
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.price
     *
     * @return the value of saled_goods.price
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.price
     *
     * @param price the value for saled_goods.price
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.count
     *
     * @return the value of saled_goods.count
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.count
     *
     * @param count the value for saled_goods.count
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.rate
     *
     * @return the value of saled_goods.rate
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.rate
     *
     * @param rate the value for saled_goods.rate
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saled_goods.comment
     *
     * @return the value of saled_goods.comment
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saled_goods.comment
     *
     * @param comment the value for saled_goods.comment
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}