package com.example.freshonline.model;

import java.math.BigDecimal;

public class StockedGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.name
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.type
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.storage
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private BigDecimal storage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.sales
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private BigDecimal sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.onsale
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Byte onsale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.sale_price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.rate
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.rate_count
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Integer rateCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.brand
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.category_id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.is_new
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private Byte isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.pic
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocked_goods.description
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.id
     *
     * @return the value of stocked_goods.id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.id
     *
     * @param id the value for stocked_goods.id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.name
     *
     * @return the value of stocked_goods.name
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.name
     *
     * @param name the value for stocked_goods.name
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.type
     *
     * @return the value of stocked_goods.type
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.type
     *
     * @param type the value for stocked_goods.type
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.price
     *
     * @return the value of stocked_goods.price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.price
     *
     * @param price the value for stocked_goods.price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.storage
     *
     * @return the value of stocked_goods.storage
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public BigDecimal getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.storage
     *
     * @param storage the value for stocked_goods.storage
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setStorage(BigDecimal storage) {
        this.storage = storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.sales
     *
     * @return the value of stocked_goods.sales
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public BigDecimal getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.sales
     *
     * @param sales the value for stocked_goods.sales
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setSales(BigDecimal sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.onsale
     *
     * @return the value of stocked_goods.onsale
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Byte getOnsale() {
        return onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.onsale
     *
     * @param onsale the value for stocked_goods.onsale
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setOnsale(Byte onsale) {
        this.onsale = onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.sale_price
     *
     * @return the value of stocked_goods.sale_price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.sale_price
     *
     * @param salePrice the value for stocked_goods.sale_price
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.rate
     *
     * @return the value of stocked_goods.rate
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.rate
     *
     * @param rate the value for stocked_goods.rate
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.rate_count
     *
     * @return the value of stocked_goods.rate_count
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Integer getRateCount() {
        return rateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.rate_count
     *
     * @param rateCount the value for stocked_goods.rate_count
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setRateCount(Integer rateCount) {
        this.rateCount = rateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.brand
     *
     * @return the value of stocked_goods.brand
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.brand
     *
     * @param brand the value for stocked_goods.brand
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.category_id
     *
     * @return the value of stocked_goods.category_id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.category_id
     *
     * @param categoryId the value for stocked_goods.category_id
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.is_new
     *
     * @return the value of stocked_goods.is_new
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public Byte getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.is_new
     *
     * @param isNew the value for stocked_goods.is_new
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setIsNew(Byte isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.pic
     *
     * @return the value of stocked_goods.pic
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.pic
     *
     * @param pic the value for stocked_goods.pic
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocked_goods.description
     *
     * @return the value of stocked_goods.description
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocked_goods.description
     *
     * @param description the value for stocked_goods.description
     *
     * @mbg.generated Fri Jan 28 11:53:04 EST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }
}