package com.example.freshonline.dao;

import com.example.freshonline.model.SaledGoods;
import com.example.freshonline.model.SaledGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaledGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    long countByExample(SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int deleteByExample(SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int deleteByPrimaryKey(@Param("orderId") Integer orderId, @Param("goodsId") Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int insert(SaledGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int insertSelective(SaledGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    List<SaledGoods> selectByExampleWithBLOBs(SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    List<SaledGoods> selectByExample(SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    SaledGoods selectByPrimaryKey(@Param("orderId") Integer orderId, @Param("goodsId") Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByExampleSelective(@Param("record") SaledGoods record, @Param("example") SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") SaledGoods record, @Param("example") SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByExample(@Param("record") SaledGoods record, @Param("example") SaledGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByPrimaryKeySelective(SaledGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByPrimaryKeyWithBLOBs(SaledGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saled_goods
     *
     * @mbg.generated Sun Feb 06 18:37:56 EST 2022
     */
    int updateByPrimaryKey(SaledGoods record);
}